name: SHRP Boot Build (sunstone)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
            libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig \
            openjdk-11-jdk python-is-python3 repo ccache

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize SHRP manifest
        run: |
          mkdir shrp
          cd shrp
          repo init -u https://github.com/SHRP-Reborn/manifest.git -b shrp-12.1

      - name: Sync SHRP sources
        run: |
          cd shrp
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Clone device, kernel, and vendor trees
        run: |
          cd shrp
          # Device tree (sunstone)
          git clone https://github.com/hpsstuff/android_device_xiaomi_sunstone.git device/xiaomi/sunstone
          # Vendor tree (stone, compatible with sunstone)
          git clone https://github.com/hpsstuff/vendor_xiaomi_stone.git vendor/xiaomi/sunstone
          # Kernel tree (stone)
          git clone https://github.com/hpsstuff/kernel_xiaomi_stone.git kernel/xiaomi/stone

      - name: Build SHRP boot image
        run: |
          cd shrp
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch twrp_sunstone-eng
          mka bootimage -j$(nproc --all)

      - name: Upload SHRP boot image
        uses: actions/upload-artifact@v4
        with:
          name: SHRP-boot-sunstone
          path: shrp/out/target/product/sunstone/boot.img
